title: Sample blog
author: Amanda the Dev
email: amandathedev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whatever whatever. Here is my description. Check it out. It's so descriptive.

# social links
twitter_username: @amandathedev
github_username:  amandathedev

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
